version: "3.7"

services:
    # image project
    appsaas:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - dminpanelsaas

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8083:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - dminpanelsaas

    # db mysql
    host1:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3383:3306"
        networks:
            - dminpanelsaas

    # redis
    redis:
        image: redis:latest
        networks:
            - dminpanelsaas

networks:
    dminpanelsaas:
        driver: bridge
